### ISSUE TITLE
error "gatsby-plugin-git-lastmod" threw an error while running the onCreatePage lifecycle

### ISSUE THREAD

**Issue by iamparthaonline** [vondenstein/gatsby-plugin-git-lastmod#9]
<img width="826" alt="image" src="https://github.com/vondenstein/gatsby-plugin-git-lastmod/assets/19206108/192d300a-9b35-4449-960f-7dfcd8937970">

I am facing this error while deploying.

**Comment by iamparthaonline** [comment]
I think I have found where the issue is happening, you have to add a try-catch handler here - 
https://github.com/vondenstein/gatsby-plugin-git-lastmod/blob/2ed3c01039ffbb8a27e7244e07e2c7289a8ed3b4/src/gatsby-node.js#L17

because in case of building in server this will end up in an error if not handled error.

**Comment by vondenstein** [comment]
Thanks for bringing this to my attention! I'll add a fix for this. 

Just so I can better understand, what is your deployment strategy when you're running into this error? It looks like it can't find the git repository for the project. Can you confirm that the directory contains a git repository? Also, does this issue still occur if you set `useFallback` to `true` in the plugin's config?

**Comment by iamparthaonline** [comment]
Hey @vondenstein I used it with useFallback flag as well, still same error. as I suggested in the [previous comment](https://github.com/vondenstein/gatsby-plugin-git-lastmod/issues/9#issuecomment-1891995850), you may add extra error handling.

**Comment by vondenstein** [comment]
Hey @iamparthaonline, I added a plugin option called `continueWithoutRepo`, which allows Gatsby build to continue if an error is encountered when the plugin loads the git repository. Could you please update to v0.2.0 and see if setting it to true solves your issue?

**Comment by vondenstein** [comment]
Closing as I believe this issue has been fixed/addressed. Feel free to re-open or open a new issue if you continue to have issues.

**Comment by iamparthaonline** [comment]
> Hey @iamparthaonline, I added a plugin option called `continueWithoutRepo`, which allows Gatsby build to continue if an error is encountered when the plugin loads the git repository. Could you please update to v0.2.0 and see if setting it to true solves your issue?

Thats a nice flag. I will use and let you know. Thanks.
